### ISSUE TITLE
Week2 Task List

### ISSUE THREAD

**Issue by snowyaya** [SplitAppTeam/Split-App-initial#3]
**Unit8:**
- [x] Updated status of issues in Project board (2pts)
- [x] Sprint planned for next week (Issues created, assigned & added to project board) (3pts)
- [x] Completed user stories checked-off in README (2pts)
- [x] Gifs created to show build progress and added to README (3pts)

Continue adding functions to the app
- [x] loginError screen
- [x] create `events` screen
- [x] `cancel` button in `addAnEvent`
- [x] `done` button in `addAnEvent`
- [x] add `members`
- [x] create `members` table in `back4app`
- [x] Discuss Paypal API
